# Generated by Django 5.0.7 on 2024-07-15 20:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Titile')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Creation_date')),
                ('file_path', models.TextField(blank=True, null=True, verbose_name='File Path')),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rating')),
                ('type', models.CharField(choices=[('MV', 'Movie'), ('TS', 'Tv_show')], max_length=2, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'FilmWork',
                'verbose_name_plural': 'FilmWork',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField(unique=True, verbose_name='Full name')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_film_works', to='films.filmwork', verbose_name='FilmWorks')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_film_works', to='films.genre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'GenreFilmWork',
                'verbose_name_plural': 'GenreFilmWork',
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(related_name='film_works', through='films.GenreFilmWork', to='films.genre', verbose_name='genres'),
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField(verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_film_works', to='films.filmwork', verbose_name='Film work')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_film_works', to='films.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'PersonFilmWork',
                'verbose_name_plural': 'PersonFilmWorks',
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date'], name='film_work_creatio_02a6ad_idx'),
        ),
    ]
