# Generated by Django 5.0.7 on 2024-07-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personfilmwork',
            name='updated_at',
        ),
    ]
